server:
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 1000
    accesslog:
      enabled: true
      pattern: common

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet : debug
    root: info
